version: '3.1'

services:
  mysql:
    build: ./third_party/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products
    ports:
      - "3306:3306"
  neo4j:
    build: ./third_party/neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/test
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_dbms_directories_import: "/"
      NEO4J_apoc_initializer_cypher: 'CALL apoc.cypher.runFile("file:///neo4jinit.cypher");'
    ports:
      - "7474:7474"
      - "7687:7687"
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    restart: unless-stopped
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
    expose:
      - "9093"
    depends_on:
      - zookeeper
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9093,OUTSIDE://_{HOSTNAME_COMMAND}:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "products-topic:1:1,users-topic:1:1"
  mongo:
    build: ./third_party/mongodb
    environment:
      MONGO_INITDB_DATABASE: admin
    command: [ --auth ]
    ports:
      - '27017-27019:27017-27019'
  producer_mysql:
    build: ./producers/mysql
    restart: unless-stopped
    depends_on:
      - mysql
      - kafka
    environment:
      - WAIT_HOSTS=mysql:3306, kafka:9092
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
  producer_neo4j:
    build: ./producers/neo4j
    restart: unless-stopped
    depends_on:
      - neo4j
      - kafka
    environment:
      - WAIT_HOSTS=neo4j:7687, kafka:9092
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
  consumer_mongo:
    build: ./consumers/mongodb
    restart: unless-stopped
    depends_on:
      - mongo
      - kafka
    environment:
      - WAIT_HOSTS=mongo:27017, kafka:9092
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
  flask_api:
    build: ./api
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - WAIT_HOSTS=mongo:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30